static const AVInputFormat * const demuxer_list[] = {
    &ff_asf_demuxer,
    &ff_avi_demuxer,
    &ff_flv_demuxer,
    &ff_gif_demuxer,
    &ff_image2_demuxer,
    &ff_matroska_demuxer,
    &ff_mov_demuxer,
    &ff_mp3_demuxer,
    &ff_mpegts_demuxer,
    &ff_pcm_s16be_demuxer,
    &ff_pcm_s16le_demuxer,
    &ff_pcm_u8_demuxer,
    &ff_wav_demuxer,
    &ff_webm_dash_manifest_demuxer,
    NULL };
